# Wazuh App Copyright (C) 2019 Wazuh Inc. (License GPLv2)
version: '2'

services:
  wazuh:
    image: wazuh/wazuh:3.9.1_6.8.0
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    depends_on:
      - logstash
  logstash:
    image: wazuh/wazuh-logstash:3.9.1_6.8.0
    hostname: logstash
    restart: always
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    environment:
      - LS_HEAP_SIZE=2048m
      - SETUP_PASSWORDS=yes
      - ELASTIC_PASSWORD=jimmyRaynor
      - LOGSTASH_PASS=Illydan
  elasticsearch:
    image: wazuh/wazuh-elasticsearch:3.9.1_6.8.0
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - node.name=node-1
      - cluster.name=wazuh
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - SETUP_PASSWORDS=yes
      - ELASTIC_PASSWORD=jimmyRaynor
      - KIBANA_PASS=zeratul
      - LOGSTASH_PASS=Illydan
      - APM_SYSTEM_PASS=kerrigan
      - BEATS_SYSTEM_PASS=artanis
      - REMOTE_USER_PASS=glorfindel
      - WAZUH_USER_PASS=Tassadar
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
  kibana:
    image: wazuh/wazuh-kibana:3.9.1_6.8.0
    hostname: kibana
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh
    environment:
      - SETUP_PASSWORDS=yes
      - ELASTIC_PASS=jimmyRaynor
      - KIBANA_PASS=zeratul
      - KIBANA_SSL_KEY_PATH=/usr/share/kibana/config/ssl/private
      - KIBANA_SSL_CERT_PATH=/usr/share/kibana/config/ssl/certs
    ports:
      - "5601:5601"
  # nginx:
  #   image: wazuh/wazuh-nginx:3.9.1_6.8.0
  #   hostname: nginx
  #   restart: always
  #   environment:
  #     - NGINX_PORT=443
  #     - NGINX_CREDENTIALS
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - kibana
  #   links:
  #     - kibana:kibana
