# Wazuh App Copyright (C) 2019 Wazuh Inc. (License GPLv2)
version: '2'

services:
  wazuh:
    image: wazuh/wazuh:3.9.1_6.8.0
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    depends_on:
      - logstash
  logstash:
    image: wazuh/wazuh-logstash:3.9.1_6.8.0
    hostname: logstash
    restart: always
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    environment:
      - LS_HEAP_SIZE=2048m
      - SETUP_PASSWORDS=yes
      - ELASTIC_PASSWORD=elastic_pass
      - LOGSTASH_PASS=logstash_pass
      - LOGSTASH_OUTPUT=https://elasticsearch:9200
      - ELASTICSEARCH_URL=https://elasticsearch:9200
  elasticsearch:
    image: wazuh/wazuh-elasticsearch:3.9.1_6.8.0
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - node.name=node-1
      - cluster.name=wazuh
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTICSEARCH_URL=https://elasticsearch:9200
      - ELASTICSEARCH_IP=https://elasticsearch
      - ELASTICSEARCH_PORT=9200
      - SETUP_PASSWORDS=yes
      - ADMIN_USER=admin_user
      - ADMIN_PASS=admin_pass
      - ELASTIC_PASSWORD=elastic_pass
      - KIBANA_PASS=kibana_pass
      - LOGSTASH_PASS=logstash_pass
      - APM_SYSTEM_PASS=apmSystem_pass
      - BEATS_SYSTEM_PASS=beatsSystem_pass
      - REMOTE_USER_PASS=remoteUser_pass
      - CA_PASS="ca_pass"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
  kibana:
    image: wazuh/wazuh-kibana:3.9.1_6.8.0
    hostname: kibana
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh
    environment:
      - ELASTICSEARCH_URL=https://elasticsearch:9200
      - SETUP_PASSWORDS=yes
      - ELASTIC_PASS=elastic_pass
      - KIBANA_PASS=kibana_pass
      - KIBANA_SSL_KEY_PATH=/usr/share/kibana/config/ssl/private
      - KIBANA_SSL_CERT_PATH=/usr/share/kibana/config/ssl/certs
      - ELASTICSEARCH_KIBANA_IP=https://elasticsearch:9200
      - CA_PASS="ca_pass"
    ports:
      - "5601:5601"